services :
  next :
    image: ghcr.io/cecilevexe/next_ci_cd/next-ci-cd:main
    restart: unless-stopped
    # ports: 
    #  - "3000:3000"
    environment :
      - DOCKER_ENV=prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.next-prod.rule=Host(`ec2-23-22-102-8.compute-1.amazonaws.com`)"
      - "traefik.http.routers.next-prod.entrypoints=web"
    networks:
      - web

networks:
  web:
    name: web
    external: true
   